title = "Presidio Workshops"
baseURL = "http://presidioworkshops.com/"
theme = "presidio"
languageCode = "en-us"
metaDataFormat = "yaml"

[params]
    description = "#FutureBuilt"

[taxonomies]
    workshop = "workshops"

[blackfriday]
    smartypants = false

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Workshops"
    identifier = "workshops"
    weight = 100


[security.exec]
allow = ['^(dart-)?sass(-embedded)?$', '^go$', '^npx$', '^postcss$', '^asciidoctor$']